name: blinkt
version: git
summary: 8 APA102 LEDs for your Raspberry Pi
description: |
  Python Library for Blinkt; 8 APA102 LEDs for your Raspberry Pi

grade: devel
confinement: devmode

apps:
  rainbow:
      command: usr/bin/python3.5 $SNAP/examples/rainbow.py

parts:
  library:
    plugin: python
    source: library
  examples:
    plugin: dump
    snap:
      - examples
